### ISSUE TITLE
Could not install package

### ISSUE THREAD

**Issue by ahmetcelebi** [PoweredSoft/DynamicLinq#6] opened 2019-03-20 07:07 UTC
I m using Visual Studio 2015 Professional and project .Net Framework 4.6.1
Install-Package : Could not install package 'PoweredSoft.DynamicLinq 1.1.8'. You are trying to install this package into a project that targets '.NETFramework
,Version=v4.6.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, con
tact the package author.
At line:1 char:1
+ Install-Package PoweredSoft.DynamicLinq
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand

**Comment by dlebee** [comment] 2019-03-20 12:15
Does 1.1.7 work?

**Comment by ahmetcelebi** [comment] 2019-03-20 12:34
Thank you for reply. My project is not .Net Core. Is this a problem? Also yes I m using VS2015

**Comment by dlebee** [comment] 2019-03-20 12:36
If you read the answer, the issue is specific to people trying to install .net standard 2.0 nuget packages on VS2015 for a .NET 4.6.1 project, unrelated to .NET Core.

You can read this stackoverflow question:
https://stackoverflow.com/questions/46788323/installing-a-netstandard-2-0-nuget-package-into-a-vs2015-net-4-6-1-project

Referencing .NET Standard 2.0 packages is supported using the following:

NuGet 3.6.0 or higher for VS 2015 (from NuGet's download site - may not yet be listed as recommended latest)
Install the ".NET Standard Support for Visual Studio 2015" from https://www.microsoft.com/net/download/core (NuGet in VS will also print a link to this in its output window).
There are a still few bugs when consuming .NET Standard 2.0 libraries, especially when mixing .NET Standard < 2.0 and 2.0 libraries but these updates give basic support.

**Comment by dlebee** [comment] 2019-03-20 14:04
@ahmetcelebi Like investigated the issue is related to the support of .NET Standard Nuget packages for 4.6.1 inside visual studio 2015.

I will close the issue.

**Closed by dlebee** 2019-03-20 14:04 UTC
